### ISSUE TITLE
Unevaluated Items

### ISSUE THREAD

**Issue by LasneF** [json-schema-org/tour#96] opened 2024-10-17 15:51 UTC
https://tour.json-schema.org/content/04-Arrays/08-Unevaluated-Items

The Unevaluated item description does not explains enought the diffrences within items keyword 
we may need to twist the requirement , so that it highlight the definitive usage of unevaluatedItems
but not sure how 

here taking the response sample and replacing unevaluatedItems by items makes the validation passing , so here it makes the differences not clear enough  

{
  "type": "object",
  "properties": {
    "name": {
      "type": "string"
    },
    "age": {
      "type": "integer"
    },
    "skills": {
      "type": "array",
      "prefixItems": [
        {
          "enum": [
            "HTML",
            "CSS",
            "JavaScript"
          ]
        },
        {
          "enum": [
            "HTML",
            "CSS",
            "JavaScript"
          ]
        },
        {
          "enum": [
            "HTML",
            "CSS",
            "JavaScript"
          ]
        }
      ],
      "items": {
        "type": "string"
      }
    }
  }
}

**Comment by jdesrosiers** [comment] 2024-10-17 23:26
Duplicate of #61. I suggest removing the lesson until it can be fixed.

**Comment by JeelRajodiya** [comment] 2024-11-02 10:28
The Unevaluated items lesson has been removed.

**Closed by JeelRajodiya** 2024-11-02 10:28 UTC
