### ISSUE TITLE
Chapter 4, Lesson 3: requirements are misleading

### ISSUE THREAD

**Issue by MartySchrader** [json-schema-org/tour#101] opened 2024-10-28 22:30 UTC
The lesson mentions specific names for the elements of the address array, yet the "solution" removes those names from the schema. Why are the field names given if they won't be used as part of the solution schema? How does the provided schema offer access to those named fields?

**Comment by JeelRajodiya** [comment] 2024-10-29 10:42
Hello @MartySchrader, thanks for the issue. 

I can see that we are missing some test cases in this lesson. Let me fix that.

**Comment by JeelRajodiya** [comment] 2024-10-29 11:58
@MartySchrader Can you please check again if the issue is still there or not?
https://tour.json-schema.org/content/04-Arrays/03-Tuple-Validation

**Comment by JeelRajodiya** [comment] 2024-11-24 08:02
Closing this as completed.

**Closed by JeelRajodiya** 2024-11-24 08:02 UTC
